"use client"
import { useSession } from "next-auth/react"
import Provider from "../components/provider/provider"
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
        const {data:session}=useSession()
  return (
    <html lang="en">
      <body>
        <Provider>
          <div>
            <h4>data {session?.user?.name}</h4>
          </div>
          {children}
        </Provider>

      </body>
    </html>
  )
}
