// "use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Provider from "../components/provider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>header-1</header>
          <Provider>
              {children}
          </Provider>
        <footer>footer1</footer>
      </body>
    </html>
  );
}
