"use client"

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Provider from "../components/provider/provider";
import { RecoilRoot } from "recoil";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-center">header-1</header>
         <div className="mx-5">
            <RecoilRoot>
              <Provider>
                {children}
              </Provider>
            </RecoilRoot>
         </div>
        <footer className="flex justify-center">footer1</footer>
      </body>
    </html>
  );
}
